name: Build and Publish Add-on

on:
  push:
    branches:
      - main
    paths:
      - 'homebox/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/homebox
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Get Add-on Info
        id: addon
        run: |
          version=$(jq --raw-output ".version" homebox/config.json)
          name=$(jq --raw-output ".name" homebox/config.json)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "name=${name}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./homebox
          file: ./homebox/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUILD_VERSION=${{ steps.addon.outputs.version }}
            BUILD_ARCH=amd64
            BUILD_NAME=${{ steps.addon.outputs.name }}
            BUILD_DESCRIPTION="HomeBox add-on for Home Assistant"
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_REF=${{ github.sha }}
            BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") 