name: Build and Publish Add-on

on:
  push:
    branches:
      - main
    paths:
      - 'homebox/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/homebox
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Get Add-on Info
        id: addon
        run: |
          version=$(jq --raw-output ".version" homebox/config.json)
          name=$(jq --raw-output ".name" homebox/config.json)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "name=${name}" >> $GITHUB_OUTPUT
          
          # Get build information for each architecture
          BUILD_FROM_AMD64=$(jq --raw-output ".build_from.amd64" homebox/build.json)
          BUILD_FROM_ARMV7=$(jq --raw-output ".build_from.armv7" homebox/build.json)
          BUILD_FROM_AARCH64=$(jq --raw-output ".build_from.aarch64" homebox/build.json)
          
          echo "build_from_amd64=${BUILD_FROM_AMD64}" >> $GITHUB_OUTPUT
          echo "build_from_armv7=${BUILD_FROM_ARMV7}" >> $GITHUB_OUTPUT
          echo "build_from_aarch64=${BUILD_FROM_AARCH64}" >> $GITHUB_OUTPUT

      # Build AMD64 version
      - name: Build and push AMD64
        uses: docker/build-push-action@v3
        with:
          context: ./homebox
          file: ./homebox/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/homebox-amd64:${{ steps.addon.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.addon.outputs.build_from_amd64 }}
            BUILD_VERSION=${{ steps.addon.outputs.version }}
            BUILD_ARCH=amd64
            BUILD_NAME=${{ steps.addon.outputs.name }}
            BUILD_DESCRIPTION="HomeBox add-on for Home Assistant"
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_REF=${{ github.sha }}
            BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")

      # Build ARMv7 version
      - name: Build and push ARMv7
        uses: docker/build-push-action@v3
        with:
          context: ./homebox
          file: ./homebox/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/homebox-armv7:${{ steps.addon.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.addon.outputs.build_from_armv7 }}
            BUILD_VERSION=${{ steps.addon.outputs.version }}
            BUILD_ARCH=armv7
            BUILD_NAME=${{ steps.addon.outputs.name }}
            BUILD_DESCRIPTION="HomeBox add-on for Home Assistant"
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_REF=${{ github.sha }}
            BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")

      # Build AARCH64 version
      - name: Build and push AARCH64
        uses: docker/build-push-action@v3
        with:
          context: ./homebox
          file: ./homebox/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/homebox-aarch64:${{ steps.addon.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.addon.outputs.build_from_aarch64 }}
            BUILD_VERSION=${{ steps.addon.outputs.version }}
            BUILD_ARCH=aarch64
            BUILD_NAME=${{ steps.addon.outputs.name }}
            BUILD_DESCRIPTION="HomeBox add-on for Home Assistant"
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_REF=${{ github.sha }}
            BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") 