name: Create Multi-Arch Manifest

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create manifest for (leave empty for latest)'
        required: false
        default: ''

jobs:
  create-manifest:
    name: Create Multi-Arch Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            version=$(jq --raw-output ".version" homebox/config.json)
            echo "version=${version}" >> $GITHUB_OUTPUT
          fi

      - name: Create and push manifest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/homebox:latest
            ghcr.io/${{ github.repository_owner }}/homebox:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          
      - name: Fix manifest
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Remove the manifest for a cleaner push
          docker manifest rm ghcr.io/${{ github.repository_owner }}/homebox:latest || true
          docker manifest rm ghcr.io/${{ github.repository_owner }}/homebox:${VERSION} || true
          
          # Create manifests
          docker manifest create ghcr.io/${{ github.repository_owner }}/homebox:latest \
            ghcr.io/${{ github.repository_owner }}/homebox-amd64:${VERSION} \
            ghcr.io/${{ github.repository_owner }}/homebox-armv7:${VERSION} \
            ghcr.io/${{ github.repository_owner }}/homebox-aarch64:${VERSION}
          
          docker manifest create ghcr.io/${{ github.repository_owner }}/homebox:${VERSION} \
            ghcr.io/${{ github.repository_owner }}/homebox-amd64:${VERSION} \
            ghcr.io/${{ github.repository_owner }}/homebox-armv7:${VERSION} \
            ghcr.io/${{ github.repository_owner }}/homebox-aarch64:${VERSION}
          
          # Push manifests
          docker manifest push ghcr.io/${{ github.repository_owner }}/homebox:latest
          docker manifest push ghcr.io/${{ github.repository_owner }}/homebox:${VERSION} 