name: Multi-Arch Build

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armv7"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Add-on Info
        id: addon
        run: |
          version=$(jq --raw-output ".version" homebox/config.json)
          echo "version=${version}" >> $GITHUB_OUTPUT
          name=$(jq --raw-output ".name" homebox/config.json)
          echo "name=${name}" >> $GITHUB_OUTPUT
          
          # Get build information for the current architecture
          build_from=$(jq --raw-output ".build_from.${{ matrix.arch }}" homebox/build.json)
          echo "build_from=${build_from}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./homebox
          file: ./homebox/Dockerfile
          platforms: ${{ matrix.arch == 'amd64' && 'linux/amd64' || matrix.arch == 'aarch64' && 'linux/arm64' || 'linux/arm/v7' }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/homebox-${{ matrix.arch }}:latest
            ghcr.io/${{ github.repository_owner }}/homebox-${{ matrix.arch }}:${{ steps.addon.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.addon.outputs.build_from }}
            BUILD_VERSION=${{ steps.addon.outputs.version }}
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_NAME=${{ steps.addon.outputs.name }}
            BUILD_DESCRIPTION="HomeBox add-on for Home Assistant"
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_REF=${{ github.sha }}
            BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") 